//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NEURAL;

namespace SSO
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SSO.SSOServiceSoap")]
    public interface SSOServiceSoap
    {
        
        // CODEGEN: Generating message contract since message AuthenticateUserRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SSO.AuthenticateUserResponse AuthenticateUser(SSO.AuthenticateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<SSO.AuthenticateUserResponse> AuthenticateUserAsync(SSO.AuthenticateUserRequest request);
        
        // CODEGEN: Generating message contract since message ChangePasswordRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SSO.ChangePasswordResponse ChangePassword(SSO.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<SSO.ChangePasswordResponse> ChangePasswordAsync(SSO.ChangePasswordRequest request);
        
        // CODEGEN: Generating message contract since message GetUserInfoRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SSO.GetUserInfoResponse GetUserInfo(SSO.GetUserInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<SSO.GetUserInfoResponse> GetUserInfoAsync(SSO.GetUserInfoRequest request);
        
        // CODEGEN: Generating message contract since message ForgotPasswordRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ForgotPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SSO.ForgotPasswordResponse ForgotPassword(SSO.ForgotPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ForgotPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<SSO.ForgotPasswordResponse> ForgotPasswordAsync(SSO.ForgotPasswordRequest request);
        
        // CODEGEN: Generating message contract since message UpdateUserPictureRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUserPicture", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SSO.UpdateUserPictureResponse UpdateUserPicture(SSO.UpdateUserPictureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUserPicture", ReplyAction="*")]
        System.Threading.Tasks.Task<SSO.UpdateUserPictureResponse> UpdateUserPictureAsync(SSO.UpdateUserPictureRequest request);
        
        // CODEGEN: Generating message contract since message LoadUserPictureRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadUserPicture", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SSO.LoadUserPictureResponse LoadUserPicture(SSO.LoadUserPictureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadUserPicture", ReplyAction="*")]
        System.Threading.Tasks.Task<SSO.LoadUserPictureResponse> LoadUserPictureAsync(SSO.LoadUserPictureRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AppCredentials
    {
        
        private string appCodeField;
        
        private string appKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AppCode
        {
            get
            {
                return this.appCodeField;
            }
            set
            {
                this.appCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AppKey
        {
            get
            {
                return this.appKeyField;
            }
            set
            {
                this.appKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserPicture
    {
        
        private byte[] pictureUserField;
        
        private string pictureContentTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] PictureUser
        {
            get
            {
                return this.pictureUserField;
            }
            set
            {
                this.pictureUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PictureContentType
        {
            get
            {
                return this.pictureContentTypeField;
            }
            set
            {
                this.pictureContentTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserInfo
    {
        
        private string nRPField;
        
        private string fullNameField;
        
        private string userEmailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NRP
        {
            get
            {
                return this.nRPField;
            }
            set
            {
                this.nRPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserEmail
        {
            get
            {
                return this.userEmailField;
            }
            set
            {
                this.userEmailField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthenticateUserRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SSO.AppCredentials AppCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Password;
        
        public AuthenticateUserRequest()
        {
        }
        
        public AuthenticateUserRequest(SSO.AppCredentials AppCredentials, string UserID, string Password)
        {
            this.AppCredentials = AppCredentials;
            this.UserID = UserID;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthenticateUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AuthenticateUserResult;
        
        public AuthenticateUserResponse()
        {
        }
        
        public AuthenticateUserResponse(bool AuthenticateUserResult)
        {
            this.AuthenticateUserResult = AuthenticateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePassword", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChangePasswordRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SSO.AppCredentials AppCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string OldPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string NewPassword;
        
        public ChangePasswordRequest()
        {
        }
        
        public ChangePasswordRequest(SSO.AppCredentials AppCredentials, string UserID, string OldPassword, string NewPassword)
        {
            this.AppCredentials = AppCredentials;
            this.UserID = UserID;
            this.OldPassword = OldPassword;
            this.NewPassword = NewPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePasswordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChangePasswordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ChangePasswordResult;
        
        public ChangePasswordResponse()
        {
        }
        
        public ChangePasswordResponse(bool ChangePasswordResult)
        {
            this.ChangePasswordResult = ChangePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserInfoRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SSO.AppCredentials AppCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserID;
        
        public GetUserInfoRequest()
        {
        }
        
        public GetUserInfoRequest(SSO.AppCredentials AppCredentials, string UserID)
        {
            this.AppCredentials = AppCredentials;
            this.UserID = UserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SSO.UserInfo GetUserInfoResult;
        
        public GetUserInfoResponse()
        {
        }
        
        public GetUserInfoResponse(SSO.UserInfo GetUserInfoResult)
        {
            this.GetUserInfoResult = GetUserInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ForgotPassword", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ForgotPasswordRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SSO.AppCredentials AppCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserID;
        
        public ForgotPasswordRequest()
        {
        }
        
        public ForgotPasswordRequest(SSO.AppCredentials AppCredentials, string UserID)
        {
            this.AppCredentials = AppCredentials;
            this.UserID = UserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ForgotPasswordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ForgotPasswordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ForgotPasswordResult;
        
        public ForgotPasswordResponse()
        {
        }
        
        public ForgotPasswordResponse(string ForgotPasswordResult)
        {
            this.ForgotPasswordResult = ForgotPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateUserPicture", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateUserPictureRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SSO.AppCredentials AppCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PictureUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ContentType;
        
        public UpdateUserPictureRequest()
        {
        }
        
        public UpdateUserPictureRequest(SSO.AppCredentials AppCredentials, string UserID, byte[] PictureUser, string ContentType)
        {
            this.AppCredentials = AppCredentials;
            this.UserID = UserID;
            this.PictureUser = PictureUser;
            this.ContentType = ContentType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateUserPictureResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateUserPictureResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UpdateUserPictureResult;
        
        public UpdateUserPictureResponse()
        {
        }
        
        public UpdateUserPictureResponse(string UpdateUserPictureResult)
        {
            this.UpdateUserPictureResult = UpdateUserPictureResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadUserPicture", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadUserPictureRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SSO.AppCredentials AppCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserID;
        
        public LoadUserPictureRequest()
        {
        }
        
        public LoadUserPictureRequest(SSO.AppCredentials AppCredentials, string UserID)
        {
            this.AppCredentials = AppCredentials;
            this.UserID = UserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadUserPictureResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadUserPictureResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SSO.UserPicture LoadUserPictureResult;
        
        public LoadUserPictureResponse()
        {
        }
        
        public LoadUserPictureResponse(SSO.UserPicture LoadUserPictureResult)
        {
            this.LoadUserPictureResult = LoadUserPictureResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface SSOServiceSoapChannel : SSO.SSOServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class SSOServiceSoapClient : System.ServiceModel.ClientBase<SSO.SSOServiceSoap>, SSO.SSOServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SSOServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SSOServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), SSOServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SSOServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SSOServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SSOServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SSOServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SSOServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SSO.AuthenticateUserResponse SSO.SSOServiceSoap.AuthenticateUser(SSO.AuthenticateUserRequest request)
        {
            return base.Channel.AuthenticateUser(request);
        }
        
        public bool AuthenticateUser(SSO.AppCredentials AppCredentials, string UserID, string Password)
        {
            SSO.AuthenticateUserRequest inValue = new SSO.AuthenticateUserRequest();
            inValue.AppCredentials = AppCredentials;
            inValue.UserID = UserID;
            inValue.Password = Password;
            SSO.AuthenticateUserResponse retVal = ((SSO.SSOServiceSoap)(this)).AuthenticateUser(inValue);
            return retVal.AuthenticateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SSO.AuthenticateUserResponse> SSO.SSOServiceSoap.AuthenticateUserAsync(SSO.AuthenticateUserRequest request)
        {
            return base.Channel.AuthenticateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<SSO.AuthenticateUserResponse> AuthenticateUserAsync(SSO.AppCredentials AppCredentials, string UserID, string Password)
        {
            SSO.AuthenticateUserRequest inValue = new SSO.AuthenticateUserRequest();
            inValue.AppCredentials = AppCredentials;
            inValue.UserID = UserID;
            inValue.Password = Password;
            return ((SSO.SSOServiceSoap)(this)).AuthenticateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SSO.ChangePasswordResponse SSO.SSOServiceSoap.ChangePassword(SSO.ChangePasswordRequest request)
        {
            return base.Channel.ChangePassword(request);
        }
        
        public bool ChangePassword(SSO.AppCredentials AppCredentials, string UserID, string OldPassword, string NewPassword)
        {
            SSO.ChangePasswordRequest inValue = new SSO.ChangePasswordRequest();
            inValue.AppCredentials = AppCredentials;
            inValue.UserID = UserID;
            inValue.OldPassword = OldPassword;
            inValue.NewPassword = NewPassword;
            SSO.ChangePasswordResponse retVal = ((SSO.SSOServiceSoap)(this)).ChangePassword(inValue);
            return retVal.ChangePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SSO.ChangePasswordResponse> SSO.SSOServiceSoap.ChangePasswordAsync(SSO.ChangePasswordRequest request)
        {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<SSO.ChangePasswordResponse> ChangePasswordAsync(SSO.AppCredentials AppCredentials, string UserID, string OldPassword, string NewPassword)
        {
            SSO.ChangePasswordRequest inValue = new SSO.ChangePasswordRequest();
            inValue.AppCredentials = AppCredentials;
            inValue.UserID = UserID;
            inValue.OldPassword = OldPassword;
            inValue.NewPassword = NewPassword;
            return ((SSO.SSOServiceSoap)(this)).ChangePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SSO.GetUserInfoResponse SSO.SSOServiceSoap.GetUserInfo(SSO.GetUserInfoRequest request)
        {
            return base.Channel.GetUserInfo(request);
        }
        
        public SSO.UserInfo GetUserInfo(SSO.AppCredentials AppCredentials, string UserID)
        {
            SSO.GetUserInfoRequest inValue = new SSO.GetUserInfoRequest();
            inValue.AppCredentials = AppCredentials;
            inValue.UserID = UserID;
            SSO.GetUserInfoResponse retVal = ((SSO.SSOServiceSoap)(this)).GetUserInfo(inValue);
            return retVal.GetUserInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SSO.GetUserInfoResponse> SSO.SSOServiceSoap.GetUserInfoAsync(SSO.GetUserInfoRequest request)
        {
            return base.Channel.GetUserInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SSO.GetUserInfoResponse> GetUserInfoAsync(SSO.AppCredentials AppCredentials, string UserID)
        {
            SSO.GetUserInfoRequest inValue = new SSO.GetUserInfoRequest();
            inValue.AppCredentials = AppCredentials;
            inValue.UserID = UserID;
            return ((SSO.SSOServiceSoap)(this)).GetUserInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SSO.ForgotPasswordResponse SSO.SSOServiceSoap.ForgotPassword(SSO.ForgotPasswordRequest request)
        {
            return base.Channel.ForgotPassword(request);
        }
        
        public string ForgotPassword(SSO.AppCredentials AppCredentials, string UserID)
        {
            SSO.ForgotPasswordRequest inValue = new SSO.ForgotPasswordRequest();
            inValue.AppCredentials = AppCredentials;
            inValue.UserID = UserID;
            SSO.ForgotPasswordResponse retVal = ((SSO.SSOServiceSoap)(this)).ForgotPassword(inValue);
            return retVal.ForgotPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SSO.ForgotPasswordResponse> SSO.SSOServiceSoap.ForgotPasswordAsync(SSO.ForgotPasswordRequest request)
        {
            return base.Channel.ForgotPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<SSO.ForgotPasswordResponse> ForgotPasswordAsync(SSO.AppCredentials AppCredentials, string UserID)
        {
            SSO.ForgotPasswordRequest inValue = new SSO.ForgotPasswordRequest();
            inValue.AppCredentials = AppCredentials;
            inValue.UserID = UserID;
            return ((SSO.SSOServiceSoap)(this)).ForgotPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SSO.UpdateUserPictureResponse SSO.SSOServiceSoap.UpdateUserPicture(SSO.UpdateUserPictureRequest request)
        {
            return base.Channel.UpdateUserPicture(request);
        }
        
        public string UpdateUserPicture(SSO.AppCredentials AppCredentials, string UserID, byte[] PictureUser, string ContentType)
        {
            SSO.UpdateUserPictureRequest inValue = new SSO.UpdateUserPictureRequest();
            inValue.AppCredentials = AppCredentials;
            inValue.UserID = UserID;
            inValue.PictureUser = PictureUser;
            inValue.ContentType = ContentType;
            SSO.UpdateUserPictureResponse retVal = ((SSO.SSOServiceSoap)(this)).UpdateUserPicture(inValue);
            return retVal.UpdateUserPictureResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SSO.UpdateUserPictureResponse> SSO.SSOServiceSoap.UpdateUserPictureAsync(SSO.UpdateUserPictureRequest request)
        {
            return base.Channel.UpdateUserPictureAsync(request);
        }
        
        public System.Threading.Tasks.Task<SSO.UpdateUserPictureResponse> UpdateUserPictureAsync(SSO.AppCredentials AppCredentials, string UserID, byte[] PictureUser, string ContentType)
        {
            SSO.UpdateUserPictureRequest inValue = new SSO.UpdateUserPictureRequest();
            inValue.AppCredentials = AppCredentials;
            inValue.UserID = UserID;
            inValue.PictureUser = PictureUser;
            inValue.ContentType = ContentType;
            return ((SSO.SSOServiceSoap)(this)).UpdateUserPictureAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SSO.LoadUserPictureResponse SSO.SSOServiceSoap.LoadUserPicture(SSO.LoadUserPictureRequest request)
        {
            return base.Channel.LoadUserPicture(request);
        }
        
        public SSO.UserPicture LoadUserPicture(SSO.AppCredentials AppCredentials, string UserID)
        {
            SSO.LoadUserPictureRequest inValue = new SSO.LoadUserPictureRequest();
            inValue.AppCredentials = AppCredentials;
            inValue.UserID = UserID;
            SSO.LoadUserPictureResponse retVal = ((SSO.SSOServiceSoap)(this)).LoadUserPicture(inValue);
            return retVal.LoadUserPictureResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SSO.LoadUserPictureResponse> SSO.SSOServiceSoap.LoadUserPictureAsync(SSO.LoadUserPictureRequest request)
        {
            return base.Channel.LoadUserPictureAsync(request);
        }
        
        public System.Threading.Tasks.Task<SSO.LoadUserPictureResponse> LoadUserPictureAsync(SSO.AppCredentials AppCredentials, string UserID)
        {
            SSO.LoadUserPictureRequest inValue = new SSO.LoadUserPictureRequest();
            inValue.AppCredentials = AppCredentials;
            inValue.UserID = UserID;
            return ((SSO.SSOServiceSoap)(this)).LoadUserPictureAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SSOServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SSOServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SSOServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress(Startup.AddressWS);
            }
            if ((endpointConfiguration == EndpointConfiguration.SSOServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress(Startup.AddressWS);
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SSOServiceSoap,
            
            SSOServiceSoap12,
        }
    }
}
